import './css/style.css';

import { Inter } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function AppLayout({
                                      children,
                                  }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="scroll-smooth">
        <body className={`${inter.variable} font-inter antialiased bg-slate-900 text-slate-100 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            {/*<Header />*/}
            {children}
            {/*<Footer />*/}
        </div>
        </body>
        </html>
    );
}
